import Head from 'next/head';
import styled, { ThemeProvider } from 'styled-components';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import GlobalStyles from '../components/GlobalStyles';
import { theme } from '../components/GlobalStyles';

import Header from '../components/Header';
import NavBar from '../components/Navbar';

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />
      <ThemeProvider theme={theme}>
        <StyledLayout>
          <StyledHeader>
            <Header />
          </StyledHeader>
          <StyledMain>
            <Component {...pageProps} />
          </StyledMain>
          <StyledFooter>
            <NavBar />
          </StyledFooter>
          <ToastContainer />
        </StyledLayout>
      </ThemeProvider>
    </>
  );
}

export default App;

const StyledLayout = styled.div`
  box-shadow: 0px 0px 20px 5px rgba(0, 0, 0, 0.1);
  display: flex;
  flex-direction: column;
  min-height: 100vh;
`;

const StyledHeader = styled.header`
  max-width: 420px;
`;

const StyledMain = styled.main`
  flex: 1;
  padding: 0 8px 70px;
`;

const StyledFooter = styled.footer`
  bottom: 0;
  max-width: 420px;
  position: fixed;
  width: 100%;
`;
